# Generated by Django 5.2.7 on 2025-10-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='cover',
        ),
    ]
