# Generated by Django 5.2.7 on 2025-10-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_image_article_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cover',
            new_name='image',
        ),
    ]
